### ISSUE TITLE
Feature Request: Allow access to settings view during break

### ISSUE THREAD

**Issue by JordyValentine** [deprint/break-time#6]
Hi there,

I use break-time for long coding sessions and it's great. However I'm not usually doing long sessions, more short bursts and I have a bad habit of leaving atom open. This means the timer keeps running and by the time I come back to atom its almost break time again.

Usually it's not an issue because I disable break-time when not needed. Occasionally I will forget to disable it though (like right now haha) so it would be nice to be able to get to the atom settings view during a break.

Thanks for the great plugin, I'll try not to be so forgetful!

**Comment by fstiewitz** [comment]
break-time pauses the timer when you're not working. By default, the timer stops every 13 minutes and continues once you press a key. If you are coding in short bursts with smaller breaks in between you could set the `Micro Interval` setting to something smaller (like 5 minutes) to detect those smaller pauses (increase `Interval Count` to compensate for the smaller `Micro Interval`).

About your feature request: I was thinking of adding a way to skip a break, something like a close button in the upper right corner. This would work too, right ? Only allowing settings-view is a bit difficult.

**Comment by JordyValentine** [comment]
Ah, thanks for your advice about changing the intervals, that would probably do the job just fine.

I was going to mention in my original post that getting only the settings view to break through would probably be pretty difficult, but I haven't looked into coding for atom, so I wasn't sure.

I think a way to skip a break would be more than enough, I love the warning you get before the break, but for some reason I keep ignoring it or think I can get a few more lines done in those last few minutes.

That said, is there maybe a subtle way you could add break skips in? Maybe in the same package menu as 'skip next break'? I just worry that if there's a big skip button people will just hit it every time and end up eventually removing the plugin

**Comment by fstiewitz** [comment]
Obviously I'm not going to place a big red button in the middle of the screen :wink: 

If people really want to skip their break they can just restart atom. I once played with the idea of making it more difficult for users to skip (like making sure that restarting atom does not reset the timer), but I dropped it because, in the end, this is just a package. People download it because they have an incentive to take regular breaks. I simply expect them to follow my package's advice and even if they don't (I occasionally skip too :disappointed:): It's their own health.

Right now, I have three ideas:

Idea 1: Place a small "X" in the top right corner of the window to skip a break.
Idea 1.1: Place a small "X", but only if the user enabled it in the settings (and don't advertise this setting in my README).
Idea 1.2: Place a small "X", but clicking it opens a text prompt, requiring the user to enter "I want to be unhealthy but productive" three times before stopping the break (as I said, you install this package for a reason and if you don't like it, don't use it).

Idea 2: Add a command (similar to `break-time:skip`) to skip the current break. The package menu is not available during a break (my package catches all commands), so if you want to stop the break, you'll have to bind it to a key and most users are too lazy to do that.

Idea 1.1 is probably enough. I just included the other two to show that I'm not too concerned about users not taking my package seriously :smiley:

**Comment by JordyValentine** [comment]
Haha, good to see a dev with a sense of humor :smile: 
I agree, I think 1.1 would be more than enough, if you wanted it hidden maybe you could have a line in the config file that the user could change and would have to download/edit/install the package manually.
That might be a bit awkward with updates in future though, again I haven't looked into Atom much further than using it

Idea 2 would definitely convince you to just take a break instead :wink:  haha, but if you were to actually implement it imagine the complaints haha

**Comment by fstiewitz** [comment]
Finally had time to implement this.
I went with 1.1. There is now a setting to display the skip button during a break (disabled by default, of course).
